package com.example.analytics

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import com.example.data.WorkItem
import com.example.security.CryptoManager
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object EODSummaryGenerator {

    fun generateAndCopy(context: Context, date: String, items: List<WorkItem>) {
        val dailyItems = items.filter { it.date == date }
        
        val completed = dailyItems.filter { it.status == "COMPLETED" }
        val pending = dailyItems.filter { it.status != "COMPLETED" }
        
        val sb = StringBuilder()
        sb.append("EOD Status Report: $date\n")
        sb.append("----------------------------\n\n")
        
        sb.append("✅ COMPLETED TODAY (\${completed.size}):\n")
        completed.forEach {
            val title = CryptoManager.decrypt(it.title)
            sb.append("- [\${it.type}] $title\n")
        }
        
        sb.append("\n⏳ PENDING / BLOCKED (\${pending.size}):\n")
        pending.forEach {
            val title = CryptoManager.decrypt(it.title)
            sb.append("- [\${it.type}] $title\n")
        }

        sb.append("\n----------------------------\n")
        sb.append("Generated by WorkMail Planner")

        val summary = sb.toString()

        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("EOD Summary", summary)
        clipboard.setPrimaryClip(clip)
        
        Toast.makeText(context, "EOD Summary copied to clipboard!", Toast.LENGTH_LONG).show()
    }
}
